# Machine Learning 1

We haven't really touched on the topic of training data and creating a model.

First, we need to create a new notebook, using a different dataset than before: the Iris dataset.

If we go to [Iris Flower](https://en.wikipedia.org/wiki/Iris_flower_data_set), it's a dataset about the Iris that actually has different types. We'll create a machine learning model that can detect types of the Iris plant.

We can use this data with __Scikit Learn__, another library that can help us with ML.

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

We now have the data loaded. We've imported the data, we don't need to clean it since the dataset is pre-built.

Next is to split the data into training sets and test it.

In [2]:
x = iris.data  # our input data
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

So, `x` is a massive array, and `y` is going to be the target.

In [3]:
iris.data
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

We want to find or create a function that takes in `x`, which will be our data, and output the `y`

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Each list is a piece of data that represents, by some parameters, the iris flower. And then we have the target, which is the answer, such that when we input this data, we get the output. But what is it?

If we look for the Iris dataset in Kaggle, in the columns are the numbers that we get in the above arrays, and each on corresponds to different types of the Iris flower.

We'll declare `x` as our Iris data, while `y` will be our target:

In [ ]:
x = iris.data
y = iris.target

And we really want to get the feature names here, because each item in the list is a feature that we want to reveal and, besides, that's what these columns in Kaggle are all about:

<br />

![kaggle-iris](./kaggle-iris.png)

<br />

So we can store this by saying

In [5]:
x = iris.data
y = iris.target

feature_names = iris.feature_names # column names (pre-defined)
target_names = iris.target_names # target names (pre-defined)
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

...and if we check out the target_names, we'll see that we have three options:

In [6]:
x = iris.data
y = iris.target

feature_names = iris.feature_names # column names (pre-defined)
target_names = iris.target_names # target names (pre-defined)
target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

Until now, we've imported the data, and we didn't have to clean what was in a pre-built dataset.

We haven't __split__ the data yet, but we're starting to get the gist of it, what it may contain. Once we've understood the data, we can start splitting it into a __training__ and __data__ set.

At the moment, we're just doing supervised learning. We have all the data that we need, and we also have the answers that we need so that we can __test__ our model.

In [7]:
type(x)

numpy.ndarray

The type comes from `numpy` library, which allows for the use of multidimensional arrays. Under the hood, this dataset is a Numpy array, a little more feature-rich than just a Python list.

So, we're going to start to split our data:

In [ ]:
from sklearn.model_selection import train_test_split # splits arrays or matrices into random train and test subsets

This will randomly decide for us how it's going to split the data into the __training data__ and the __test data__.

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2) # 80% training and 20% test
print(x_train.shape)
print(x_test.shape)

(120, 4)
(30, 4)


This returns a __*dimensionality*__ of the array: how many rows and columns exist there. We can change the value of `test_size` however we wish.
But we want to have more training than test data because our model improves with the more data we give it. THe same applies to the `y_train` and `y_test` variables.